from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt

from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten
from keras.utils import to_categorical

from keras.datasets import cifar10
(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

# EXPLORE THE DATA
print('Training data shape : ', train_images.shape, train_labels.shape)  # (50000, 32, 32, 3) (50000, 1)
print('Testing data shape : ', test_images.shape, test_labels.shape)     # (10000, 32, 32, 3) (10000, 1)

# Find the unique numbers from the train labels
classes = np.unique(train_labels)
nClasses = len(classes)
print('Total number of outputs : ', nClasses)  # 10
print('Output classes : ', classes)            # [0 1 2 3 4 5 6 7 8 9]

# plt.figure(figsize=[4,2])
# # Display the first image in training data
# plt.subplot(121)
# plt.imshow(train_images[0,:,:], cmap='gray')
# plt.title("Ground Truth : {}".format(train_labels[0]))
# # Display the first image in testing data
# plt.subplot(122)
# plt.imshow(test_images[0,:,:], cmap='gray')
# plt.title("Ground Truth : {}".format(test_labels[0]))
# plt.savefig("../res/cifar10/images.jpg")

# Find the shape of input images and create the variable input_shape
nRows,nCols,nDims = train_images.shape[1:]
train_data = train_images.reshape(train_images.shape[0], nRows, nCols, nDims)
test_data = test_images.reshape(test_images.shape[0], nRows, nCols, nDims)
input_shape = (nRows, nCols, nDims)

# Change to float datatype
train_data = train_data.astype('float32')
test_data = test_data.astype('float32')

# Scale the data to lie between 0 to 1
train_data /= 255
test_data /= 255

# Change the labels from integer to categorical data
train_labels_one_hot = to_categorical(train_labels)
test_labels_one_hot = to_categorical(test_labels)

# Display the change for category label using one-hot encoding
print('Original label 0 : ', train_labels[0])
print('After conversion to categorical ( one-hot ) : ', train_labels_one_hot[0])


# SET UP TRAINING NETWORK
def createModel():
    model = Sequential()
    model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=input_shape))
    model.add(Conv2D(32, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nClasses, activation='softmax'))

    return model

# # without augmentation
# model = createModel()
# batch_size = 256
# epochs = 100
# model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
#
# history = model.fit(train_data, train_labels_one_hot, batch_size=batch_size, epochs=epochs, verbose=1,
#                     validation_data=(test_data, test_labels_one_hot))
#
# model.evaluate(test_data, test_labels_one_hot)
#
# # LOSS & ACCURACY CURVES
# # Loss Curves
# plt.figure(figsize=[8, 6])
# plt.plot(history.history['loss'], 'r', linewidth=3.0)
# plt.plot(history.history['val_loss'], 'b', linewidth=3.0)
# plt.legend(['Training loss', 'Validation Loss'], fontsize=18)
# plt.xlabel('Epochs ', fontsize=16)
# plt.ylabel('Loss', fontsize=16)
# plt.title('Loss Curves', fontsize=16)
# plt.savefig("../res/cifar10/loss_curves.jpg")
#
# # Accuracy Curves
# plt.figure(figsize=[8, 6])
# plt.plot(history.history['acc'], 'r', linewidth=3.0)
# plt.plot(history.history['val_acc'], 'b', linewidth=3.0)
# plt.legend(['Training Accuracy', 'Validation Accuracy'], fontsize=18)
# plt.xlabel('Epochs ', fontsize=16)
# plt.ylabel('Accuracy', fontsize=16)
# plt.title('Accuracy Curves', fontsize=16)
# plt.savefig("../res/cifar10/acc_curves.jpg")


# with augmentation
from keras.preprocessing.image import ImageDataGenerator

model2 = createModel()

model2.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

batch_size = 256
epochs = 100
datagen = ImageDataGenerator(
    zoom_range=0.2,  # randomly zoom into images
    rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
    width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
    height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
    horizontal_flip=True,  # randomly flip images
    vertical_flip=False)  # randomly flip images

# Fit the model on the batches generated by datagen.flow().
history2 = model2.fit_generator(datagen.flow(train_data, train_labels_one_hot, batch_size=batch_size),
                                steps_per_epoch=int(np.ceil(train_data.shape[0] / float(batch_size))),
                                epochs=epochs,
                                validation_data=(test_data, test_labels_one_hot),
                                workers=4)

model2.evaluate(test_data, test_labels_one_hot)

# Loss Curves
plt.figure(figsize=[8, 6])
plt.plot(history2.history['loss'], 'r', linewidth=3.0)
plt.plot(history2.history['val_loss'], 'b', linewidth=3.0)
plt.legend(['Training loss', 'Validation Loss'], fontsize=18)
plt.xlabel('Epochs ', fontsize=16)
plt.ylabel('Loss', fontsize=16)
plt.title('Loss Curves', fontsize=16)
plt.savefig("../res/cifar10/loss_curves_aug.jpg")

# Accuracy Curves
plt.figure(figsize=[8, 6])
plt.plot(history2.history['acc'], 'r', linewidth=3.0)
plt.plot(history2.history['val_acc'], 'b', linewidth=3.0)
plt.legend(['Training Accuracy', 'Validation Accuracy'], fontsize=18)
plt.xlabel('Epochs ', fontsize=16)
plt.ylabel('Accuracy', fontsize=16)
plt.title('Accuracy Curves', fontsize=16)
plt.savefig("../res/cifar10/acc_curves_aug.jpg")

model2.save("../res/cifar10/cifar10-aug.h5")